apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vikunja
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: vikunja
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 10220
          volumeMounts:
            - name: vikunja-files
              mountPath: /app/vikunja/files
            - name: vikunja-config
              mountPath: /etc/vikunja/config.yaml
              subPath: config.yaml
      volumes:
        - name: vikunja-files
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-vikunja-pvc
        - name: vikunja-config
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ .Release.Name }}-vikunja-config
