apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vikunja-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config.yaml: {{ .Values.vikunja.config | b64enc | quote }}
