apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vikunja
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3456
  selector:
    app: {{ .Chart.Name }}

