replicaCount: 1

image:
  repository: vikunja/vikunja
  tag: "latest"
  pullPolicy: IfNotPresent

vikunja:
  publicURL: http://vikunja.local
  jwtSecret: dskfj23kkjsdkjsdfjkl3sdfgfsdfhsdfkh3ozxpqzx

database:
  host: mariadb-mariadb-0.mariadb-mariadb.default.svc.cluster.local
  port: 3306
  user: vikunja
  password: changeme
  name: vikunja
  type: mysql

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP
  port: 3456

resources: {}

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
service:
  port: 80

