replicaCount: 1

image:
  repository: vikunja/vikunja
  tag: "latest"
  pullPolicy: IfNotPresent

vikunja:
  publicURL: http://vikunja.local
  jwtSecret: dskfj23kkjsdkjsdfjkl3sdfgfsdfhsdfkh3ozxpqzx
  config: |
    database:
      type: mysql
      user: vikunja
      password: changeme
      host: mariadb-mariadb.default.svc.cluster.local
    service:
      interface: :10220
      JWTSecret: k7TWkTwmZXq7LtEvvt8SPdJ9ohUJh5mE
      timezone: "UTC"
      maxitemsperpage: 50
      enablecaldav: true
      enablelinksharing: true
      enableuserdeletion: true
      enabletaskattachments: true
      enabletop: true
      enableemailreminders: true
      maxavatarsize: 1024

    log:
      enabled: true
      path: "/app/vikunja/logs"
      level: "INFO"

    auth:
      openid:
        enabled: true
        redirecturl: "https://vikunja.vikunja.click/auth/openid/"
        providers:
          - name: "Keycloak"
            authurl: "https://keycloak.vikunja.click/realms/vikunja"
            logouturl: "http://keycloak.vikunja.click/realms/vikunja/protocol/openid-connect/logout"
            clientid: "vikunja"
            clientsecret: "0uh22R3P6U7bY3uJmmxZxAZbP5fadtPD"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
     cpu: 1
     memory: 1Gi
  requests:
     cpu: "512m"
     memory: "512Mi"
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:039612885735:certificate/d80198c4-0b80-4548-91af-b2a37a287239
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'

service:
  port: 10220
