replicaCount: 1

image:
  repository: mariadb
  tag: "10"
  pullPolicy: IfNotPresent

mariadb:
  rootPassword: supersecret
  user: vikunja
  password: changeme
  database: vikunja

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
