apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: 3306
      targetPort: mysql
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
