apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  serviceName: mariadb
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_USER
              value: "{{ .Values.env.MYSQL_USER }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.env.MYSQL_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.env.MYSQL_DATABASE }}"
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          emptyDir: {}  # Using emptyDir to store data temporarily
